apiVersion: v2
appVersion: s4.9
dependencies:
  - name: elasticsearch
    condition: elasticsearch.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: ^22.0.4
  - name: minio
    condition: minio.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: ^12.8.0
  - name: postgresql
    condition: postgresql.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: ^16.7.4
  - name: rabbitmq
    condition: rabbitmq.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: ^16.0.3
  - name: redis
    condition: redis.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
    version: ^21.1.6
description: Official Helm chart for Mayan EDMS
home: https://www.mayan-edms.com/
icon: https://www.mayan-edms.com/favicon.ico
keywords:
  - django
  - dms
  - edms
  - mayan-edms
  - python
  - document-management
maintainers:
  - name: Roberto Rosario
    email: roberto.rosario@mayan-edms.com
name: mayanedms
sources:
  - https://gitlab.com/mayan-edms/mayan-edms
type: application
version: 4.9
